# Generated by Django 3.0.6 on 2020-06-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='party_id',
            new_name='id',
        ),
    ]
