# Generated by Django 3.0.6 on 2020-06-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20200602_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='party slug'),
        ),
    ]
