# Generated by Django 3.0.6 on 2020-06-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_auto_20200602_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='id',
            field=models.SlugField(max_length=7, primary_key=True, serialize=False, verbose_name='party slug'),
        ),
    ]
